config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/about'

  devise_for :users

  resources :users do
    resources :registered_applications, only: [:create, :show, :destroy]
  end

  
  authenticated :user do
    root :to => 'users#show'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  namespace :api, defaults: { format: :json } do
    match 'create_event', to: 'events#create', via: [:options]
    resources :events, only: [:create]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application



end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
has_many :events, dependent: :destroy
belongs_to :user

    def event_count
    events.count
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications, dependent: :destroy
  #has_many :events

  
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

  skip_before_action :verify_authenticity_token

  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end


  def create
      registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = registered_application.events.build(event_params)
        if @event.save
          render json: @event, status: :created
        else
          render @event.errors, status: :unprocessable_entity
        end
    end
  end

private

  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/api/events_controller_old.rb
#class EventsController < ApplicationController
  
 # def new
  #  @registered_application = RegisteredApplication.find(params[:registered_application_id])
   # @event = Event.new
   # @event.registered_application = @registered_application
   # @registered_application.user = @user
   # authorize @event
 # end

  #def create
  #end

 # def show
  #  @event = Event.find
   # @registered_application = RegisteredApplication.find(params[:registered_application_id])
   # @registered_application.user = @user
   # authorize @event
  #end

  #def destroy
  #end


 #end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @registered_application = @user.registered_applications.build(registered_application_params)
    authorize @registered_application
    if @registered_application.save
      flash[:notice] = "Application was registered"
      redirect_to [@user]
    else
      flash[:notice] = "There was an error registering your application"
      render :new
    end
  end

  def show
    
  end

  def update
  end

  def destroy
    @user = User.find(params[:user_id])
    @registered_application = @user.registered_applications.find(params[:id])
    authorize @registered_application
      if @registered_application.destroy
        flash[:notice] = "Application was deleted successfully." 
      else
        flash[:error] = "There was an error deleting the application."
      end

      respond_to do |format|
       format.html
       format.js
      end
  end

  private

    def registered_application_params
      params.require(:registered_application).permit(:name, :url)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end

  def show
    @registered_applications=current_user.registered_applications
  end

  #def create
  #end

  #def update
  #end

  #def destroy
  #end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

   def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <ul class="nav nav-tabs">
          <li><%= link_to "Blocmetrics", root_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>

          <div class="pull-right user-info">
            <% if current_user %>
              Hello <%= current_user.email %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
            <% end %>
          </div>

        </ul>

      <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
          <% end %>
      <%= yield %>
    </div>

    



</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for [user, registered_application] do |f| %>
  <% if registered_application.errors.any? %>
    <div class= "alert alert-danger">
      <h4>There are <%= pluralize(registered_application.errors.count, "error") %>.</h4>
      <ul>
        <% registered_application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>


    <div class= "form-inline">
      <%= form_group_tag(registered_application.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <% end %>

        <%= form_group_tag(registered_application.errors[:url]) do %>
        <%= f.label :url, "URL" %> 
        <%= f.text_field :url, class: 'form-control' %>
      <% end %>

      <div class="form-group">
        <%= f.submit "Register Application", class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>

app/views/registered_applications/_registered_application.html.erb
<%= content_tag :div, class: 'media', id: "registered_application-#{registered_application.id}" do %>
  
      <p><b>Name:</b><%= registered_application.name %> 
        <br/>
      <b>URL:</b><%= link_to registered_application.url %>
      <br/>
      <%= pie_chart registered_application.events.group(:name).count %>
      <%= line_chart registered_application.events.group_by_day(:created_at).count %>
      <% if policy(registered_application).destroy? %>
        <br/>
        <small><%= link_to "Delete", [registered_application.user, registered_application], method: :delete, remote: true %></small> </p>
      <% end %>
<% end %>

app/views/registered_applications/create.html.erb
<h1>RegisteredApplications#create</h1>
<p>Find me in app/views/registered_applications/create.html.erb</p>

app/views/registered_applications/destroy.js.erb
<% if @registered_application.destroyed? %>
   $('#registered_application-' +<%= @registered_application.id %>).hide();
 <% else %>
   $('#registered_application-' +<%= @registered_application.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
 <% end %>

app/views/registered_applications/update.html.erb
<h1>RegisteredApplications#update</h1>
<p>Find me in app/views/registered_applications/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class ="media-body">
  <h2 class="media-heading"><%= current_user.name %></h2>
</div>

<div class="col-md-8">
  <%= render partial: 'registered_applications/registered_application', collection: @registered_applications %>
</div>

 <div class="col-md-4"> 
 <% if policy(RegisteredApplication.new).create? %>
  <div class='new-registered_application'>
    <%= render partial: 'registered_applications/form', locals: {user: current_user, registered_application: RegisteredApplication.new} %>
    <% end %>
  </div>
</div> 


</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>